# Walmart Retail Mapping Dictionary
# Maps anonymized store/department IDs to realistic US cities and department categories.

STORE_CITIES = {
    1: "Bentonville, AR (HQ)",
    2: "Dallas, TX",
    3: "Chicago, IL",
    4: "Houston, TX",
    5: "Atlanta, GA",
    6: "Miami, FL",
    7: "Phoenix, AZ",
    8: "Los Angeles, CA",
    9: "San Antonio, TX",
    10: "San Diego, CA",
    11: "Philadelphia, PA",
    12: "San Jose, CA",
    13: "Austin, TX",
    14: "Jacksonville, FL",
    15: "Fort Worth, TX",
    16: "Columbus, OH",
    17: "Charlotte, NC",
    18: "San Francisco, CA",
    19: "Indianapolis, IN",
    20: "Seattle, WA",
    21: "Denver, CO",
    22: "Boston, MA",
    23: "El Paso, TX",
    24: "Nashville, TN",
    25: "Detroit, MI",
    26: "Oklahoma City, OK",
    27: "Portland, OR",
    28: "Las Vegas, NV",
    29: "Memphis, TN",
    30: "Louisville, KY",
    31: "Baltimore, MD",
    32: "Milwaukee, WI",
    33: "Albuquerque, NM",
    34: "Tucson, AZ",
    35: "Fresno, CA",
    36: "Sacramento, CA",
    37: "Kansas City, MO",
    38: "Mesa, AZ",
    39: "Virginia Beach, VA",
    40: "Atlanta, GA (North)",
    41: "Omaha, NE",
    42: "Colorado Springs, CO",
    43: "Raleigh, NC",
    44: "Minneapolis, MN",
    45: "Tampa, FL"
}

DEPT_NAMES = {
    1: "Candy & Tobacco",
    2: "Cosmetics & HABA",
    3: "Stationery & School",
    4: "Household Paper Goods",
    5: "Media & DVDs",
    6: "Photo & Portrait",
    7: "Toys & Hobbies",
    8: "Pets & Supplies",
    9: "Sporting Goods",
    10: "Automotive Accessories",
    11: "Hardware & Tools",
    12: "Paint & Decorating",
    13: "Household Chemicals",
    14: "Kitchen & Cookware",
    16: "Lawn & Garden",
    17: "Home Decor & Candles",
    18: "Seasonal Accessories",
    19: "Crafts & Sewing",
    20: "Bath & Bedding",
    21: "Books & Magazines",
    22: "Bedding Linens",
    23: "Furniture & Decor",
    24: "Office Products",
    25: "Consumer Electronics",
    26: "Computers & Software",
    27: "Phones & Wireless",
    28: "Home Audio & Theatre",
    29: "Cameras & Optics",
    30: "Small Appliances",
    31: "Large Appliances",
    32: "Smart Home & Automation",
    33: "Musical Instruments",
    34: "Luggage & Travel",
    35: "Fitness Equipment",
    36: "Outdoor Sports",
    37: "Indoor Sports",
    38: "Apparel - Men's",
    39: "Apparel - Women's",
    40: "Apparel - Kids & Baby",
    41: "Footwear - Men's",
    42: "Footwear - Women's",
    43: "Footwear - Kids & Athletic",
    44: "Jewelry & Watches",
    45: "Bags & Leather Goods",
    46: "Dry Grocery",
    47: "Bakery & Desserts",
    48: "Fresh Produce",
    49: "Meat & Poultry",
    50: "Seafood & Fish",
    51: "Dairy & Eggs",
    52: "Frozen Foods",
    54: "Deli & Prepared Meals",
    55: "Beverages & Water",
    56: "Snacks & Confectionery",
    58: "Canned & Packaged Foods",
    59: "Baking & Condiments",
    60: "International Foods",
    65: "Health & Pharmacy",
    67: "Personal Care",
    71: "Baby Products",
    72: "Toys - Preschool",
    74: "Seasonal Apparel",
    77: "Luggage & Accessories",
    78: "Party Supplies",
    79: "Greeting Cards",
    80: "Party Accessories",
    81: "Garden Center",
    82: "Outdoor Living",
    83: "Grills & Patio Furniture",
    85: "Storage & Organization",
    87: "Home Improvement",
    90: "Grocery - Bulk",
    91: "Apparel - Intimates",
    92: "Apparel - Activewear",
    93: "Beauty & Fragrance",
    94: "Personal Care - Hair",
    95: "Personal Care - Body",
    96: "Household Cleaners",
    97: "Apparel - Accessories",
    98: "Apparel - Maternity",
    99: "Dry Grocery - Baking"
}

def get_store_label(store_id):
    if store_id is None:
        return "All Stores"
    city = STORE_CITIES.get(int(store_id), "Unknown")
    return f"Store #{store_id} ({city})"

def get_dept_label(dept_id):
    if dept_id is None:
        return "All Departments"
    name = DEPT_NAMES.get(int(dept_id), "General Dept")
    return f"Dept #{dept_id} ({name})"
